### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by neizmirasego** [warmfusion/sensu-extension-snmptrap#8]
Hi! 

Could you please help me with figuring out what is wrong because I am not very good at ruby. I got this error when trying to restart sensu-client.
```
/etc/sensu/extensions/extension-snmptrap.rb:89:in `options': undefined method `[]' for nil:NilClass (NoMethodError)
        from /etc/sensu/extensions/extension-snmptrap.rb:105:in `validate'
        from /etc/sensu/extensions/extension-snmptrap.rb:113:in `post_init'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-extension-1.5.0/lib/sensu/extension.rb:19:in `block in initialize'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:977:in `block in run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `times'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:974:in `run_deferred_callbacks'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.7/lib/sensu/client/process.rb:18:in `run'
        from /opt/sensu/embedded/lib/ruby/gems/2.3.0/gems/sensu-0.25.7/exe/sensu-client:10:in `<top (required)>'
        from /opt/sensu/bin/sensu-client:22:in `load'
        from /opt/sensu/bin/sensu-client:22:in `<main>'

```
Thanks!

**Comment by warmfusion** [comment]
That appears to be caused by the script being run without having any values for the sensu-client's tcp socket.

I see from the stack that you're using Sensu 0.25.7, but can you show me the configuration of the plugin too?

It may be that the plugin doesn't work on sensu 0.25+ (I've not tested it recently)

**Comment by neizmirasego** [comment]
Toby, sorry for bothering, I have managed to resolve it. 
First I have defined "client_socket_bind" and "client_socket_port" in snmp.json and placed it to /etc/sensu/conf.d. But that was not enough.
Then I added extra section "socket" in client.json and the error has gone. Looks like I missed instructions about sensu-client's tcp socket configuration.

**Comment by warmfusion** [comment]
Glad you've been able to sort it
